# ---------- パッケージ情報 ----------

# パッケージ名
name: achievement_list

# パッケージの説明
description: A new Flutter project.

# パッケージをPublishする時に必要になるオプション
# (Pluginとしてpub.devにリリースする場合にはこのオプションは削除)
publish_to: 'none'

# パッケージのバージョン(とビルド番号)
version: 1.0.0+1

# ---------- パッケージのビルド環境 ----------

environment:
  # Dartのバージョン
  sdk: ">=2.12.0 <3.0.0"

# ---------- 外部ライブラリの利用 ----------

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  # iOSアプリスタイルのアイコン
  cupertino_icons: ^0.1.3
  # ListTileのスライド
  flutter_slidable:
  # データ保存
  shared_preferences:
  # Flutter Linter
  flutter_lints:
  #DataFormat
  intl:

# ---------- 開発時用途のライブラリの利用 ----------

dev_dependencies:
  # Flutter テストライブラリ
  flutter_test:
    sdk: flutter

# ---------- アセット(デザイン・画像・フォント等)の設定 ----------

flutter:
  uses-material-design: true

###########################################################
# ★参考
# https://qiita.com/kurun_pan/items/76e13bfd03fd3dec1e27
###########################################################